# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "rpool_fb28s1/nixos/ROOT/default";
    fsType = "zfs";
    options = ["zfsutil" "X-mount.mkdir"];
  };

  fileSystems."/boot" = {
    device = "bpool_fb28s1/nixos/BOOT/default";
    fsType = "zfs";
    options = ["zfsutil" "X-mount.mkdir"];
  };

  fileSystems."/nix" = {
    device = "rpool_fb28s1/nixos/DATA/local/nix";
    fsType = "zfs";
    options = ["zfsutil" "X-mount.mkdir"];
  };

  fileSystems."/home" = {
    device = "rpool_fb28s1/nixos/DATA/default/home";
    fsType = "zfs";
    options = ["zfsutil" "X-mount.mkdir"];
  };

  fileSystems."/root" = {
    device = "rpool_fb28s1/nixos/DATA/default/root";
    fsType = "zfs";
    options = ["zfsutil" "X-mount.mkdir"];
  };

  fileSystems."/srv" = {
    device = "rpool_fb28s1/nixos/DATA/default/srv";
    fsType = "zfs";
    options = ["zfsutil" "X-mount.mkdir"];
  };

  fileSystems."/usr/local" = {
    device = "rpool_fb28s1/nixos/DATA/default/usr/local";
    fsType = "zfs";
    options = ["zfsutil" "X-mount.mkdir"];
  };

  fileSystems."/var/log" = {
    device = "rpool_fb28s1/nixos/DATA/default/var/log";
    fsType = "zfs";
    options = ["zfsutil" "X-mount.mkdir"];
  };

  fileSystems."/var/spool" = {
    device = "rpool_fb28s1/nixos/DATA/default/var/spool";
    fsType = "zfs";
    options = ["zfsutil" "X-mount.mkdir"];
  };

  fileSystems."/state" = {
    device = "rpool_fb28s1/nixos/DATA/default/state";
    fsType = "zfs";
    options = ["zfsutil" "X-mount.mkdir"];
  };

  fileSystems."/etc/nixos" = {
    device = "/state/etc/nixos";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/etc/cryptkey.d" = {
    device = "/state/etc/cryptkey.d";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/boot/efis/nvme-SKHynix_HFS512GDE9X081N_CD13N445112003740-part1" = {
    device = "/dev/disk/by-uuid/7DDD-F901";
    fsType = "vfat";
    options = ["x-systemd.idle-timeout=1min" "x-systemd.automount" "noauto"];
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
